[package]
name = "fsn"
version = "0.0.0"
authors = [ "Viktor D. <dudnik.0x76@gmail.com>" ]
description = "File Structure Notation (.fsn) format parser"
license = "MIT"
edition = "2021"

[dependencies]
